import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
const result = await build({ entryPoints: ["src/widget.ts"], bundle: true, write: false, format: "esm", platform: "browser", minify: true });
const html = await readFile("src/widget.html", "utf8");
await writeFile("src/widget.generated.ts", `// Generated by npm run build:widget. Do not edit.\nexport default ${JSON.stringify(html.replace("/* BUNDLED_WIDGET */", () => result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script")))};\n`);
